In [1]:
!pip3 install opencv-python
import numpy as np
import cv2

In [2]:
body_classifier = cv2.CascadeClassifier('haarcascade_fullbody.xml')

In [3]:
image = cv2.imread('beach_crop1.jpg')
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('img',image)
cv2.waitKey(0)

-1

In [4]:
bodies = body_classifier.detectMultiScale(gray,1.05,10)
print(bodies)

[[ 83   6  33  65]
 [ 59  11  33  65]
 [  7  62  40  81]
 [ 98  45  39  78]
 [293  86  53 106]
 [221  89  61 122]]


In [5]:
l=[]
i=1
lf=[]
for (x,y,w,h) in bodies:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)
    s=str(i)
    cv2.putText(image,s,(x,y),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
    i+=1
    l=[]
    l.append(x)
    l.append(y)
    lf.append(l)
    print(l)
print(lf)

[83, 6]
[59, 11]
[7, 62]
[98, 45]
[293, 86]
[221, 89]
[[83, 6], [59, 11], [7, 62], [98, 45], [293, 86], [221, 89]]


In [6]:
close_persons=""
import math
for i in range(len(lf)):
    print(lf[i])
    for j in range(i+1,len(lf)):
        print(lf[j])
        d=math.sqrt(((lf[j][1]-lf[i][1])**2)+(lf[j][0]-lf[i][0])**2)
        print("P"+str(i+1)+" - "+"P"+str(j+1)+" = "+str(d))
    
        if d<72.5:
            close_persons+="Person"+str(i+1)+" and Person"+str(j+1)+"; "
            cv2.line(image,(lf[i][0],lf[i][1]),(lf[j][0],lf[j][1]),(255,0,0),2)

close_persons+=" are not following social distancing"
print(close_persons)

[83, 6]
[59, 11]
P1 - P2 = 24.515301344262525
[7, 62]
P1 - P3 = 94.40338976964757
[98, 45]
P1 - P4 = 41.78516483155236
[293, 86]
P1 - P5 = 224.72205054244233
[221, 89]
P1 - P6 = 161.0372627685903
[59, 11]
[7, 62]
P2 - P3 = 72.83543093852057
[98, 45]
P2 - P4 = 51.73973328110612
[293, 86]
P2 - P5 = 245.72545655670274
[221, 89]
P2 - P6 = 179.79988876526036
[7, 62]
[98, 45]
P3 - P4 = 92.57429448826494
[293, 86]
P3 - P5 = 287.0052264332481
[221, 89]
P3 - P6 = 215.6965461012299
[98, 45]
[293, 86]
P4 - P5 = 199.2636444512646
[221, 89]
P4 - P6 = 130.6330739131557
[293, 86]
[221, 89]
P5 - P6 = 72.06247289678588
[221, 89]
Person1 and Person2; Person1 and Person4; Person2 and Person4; Person5 and Person6;  are not following social distancing


In [7]:
cv2.imshow('Distance',image)
cv2.waitKey(0)

-1